import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useQuery } from "@apollo/client";
import { GET_LOCATIONS, GET_LOCATION } from "../graphql/location";
import { Location } from "../graphql/gql/graphql";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { loading, error, data } = useQuery(GET_LOCATIONS);
  const { data: location } = useQuery(GET_LOCATION, {
    variables: { locationId: "loc-1" },
  });
  console.log(location, "location !!");

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error : {error.message}</p>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data?.locations?.map((location: Location) => (
          <div key={location.id}>
            <h1>{location.name}</h1>
            <p>{location.description}</p>
          </div>
        ))}
        {location && (
          <div>
            <p>===========================</p>
            <h1>{location.location.name}</h1>
            <p>{location.location.description}</p>
          </div>
        )}
      </main>
    </>
  );
}
